export const SHORT_FILM_MAX_DURATION = 40;

export const MOVIES_WIDTH_LIMIT1 = 1280;
export const MOVIES_WIDTH_LIMIT2 = 938;
export const MOVIES_WIDTH_LIMIT3 = 638;

export const INITIAL_MOVIES_COUNT_FOR_LIMIT1_WIDTH = 12;
export const INITIAL_MOVIES_COUNT_FOR_LIMIT2_WIDTH = 9;
export const INITIAL_MOVIES_COUNT_FOR_LIMIT3_WIDTH = 8;
export const INITIAL_MOVIES_COUNT_FOR_DOWN_LIMIT3_WIDTH = 5;

export const ADD_MOVIES_COUNT_FOR_LIMIT1_WIDTH = 4;
export const ADD_MOVIES_COUNT_FOR_LIMIT2_WIDTH = 3;
export const ADD_MOVIES_COUNT_FOR_LIMIT3_WIDTH = 3;
export const ADD_MOVIES_COUNT_FOR_DOWN_LIMIT3_WIDTH = 2;
